name: Prettier

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Prettify code
      uses: creyD/prettier_action@v3.0
      with:
        prettier_options: --write **/*.{html,js,md}
        commit_message: 'docs: prettify code'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
